### ISSUE TITLE
[Fix] 문자 중계 오류 시 예외 처리

### ISSUE THREAD

**Issue by gjeodnd12165** [VictoryFairy/VictoryFairy-backend#45]
## 🤷‍♂️ Description

경기가 취소 되는 등 문자 중계 API에서 오류 페이지를 반환할 시 예외 처리가 되어있지 않습니다.

## ⚙ Environments

- OS: [e.g. Windows]
- Browser [e.g. Chrome, Safari]
- Version [e.g. 100]

**Comment by gjeodnd12165** [comment]
에러 로그 첨부
```
api         | /usr/src/app/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:331
api         |             throw new QueryFailedError(query, parameters, err)
api         |                   ^
api         | 
api         | 
api         | QueryFailedError: invalid input syntax for type integer: "NaN"
api         |     at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:331:19)
api         |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api         |     at UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/src/query-builder/UpdateQueryBuilder.ts:145:33)
api         |     at <anonymous> (/usr/src/app/src/services/game.service.ts:87:7)
api         |     at EntityManager.transaction (/usr/src/app/node_modules/typeorm/entity-manager/src/entity-manager/EntityManager.ts:154:28)
api         |     at GameService.updateCurrentStatus (/usr/src/app/src/services/game.service.ts:82:12)
api         |     at CronJob.<anonymous> (/usr/src/app/src/services/scheduling.service.ts:98:11) {
api         |   query: 'UPDATE "game" SET "id" = $1, "date" = $2, "time" = $3, "status" = $4, "home_team_score" = $5, "away_team_score" = $6 WHERE "id" = $7',
api         |   parameters: [
api         |     '20240808NCLT0',
api         |     '2024-08-08',
api         |     '18:30:00',
api         |     '우천취소',
api         |     NaN,
api         |     NaN,
api         |     '20240808NCLT0'
api         |   ],
api         |   driverError: error: invalid input syntax for type integer: "NaN"
api         |       at /usr/src/app/node_modules/pg/lib/client.js:526:17
api         |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
api         |       at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/src/driver/postgres/PostgresQueryRunner.ts:260:25)
api         |       at UpdateQueryBuilder.execute (/usr/src/app/node_modules/typeorm/query-builder/src/query-builder/UpdateQueryBuilder.ts:145:33)
api         |       at <anonymous> (/usr/src/app/src/services/game.service.ts:87:7)
api         |       at EntityManager.transaction (/usr/src/app/node_modules/typeorm/entity-manager/src/entity-manager/EntityManager.ts:154:28)
api         |       at GameService.updateCurrentStatus (/usr/src/app/src/services/game.service.ts:82:12)
api         |       at CronJob.<anonymous> (/usr/src/app/src/services/scheduling.service.ts:98:11) {
api         |     length: 146,
api         |     severity: 'ERROR',
api         |     code: '22P02',
api         |     detail: undefined,
api         |     hint: undefined,
api         |     position: undefined,
api         |     internalPosition: undefined,
api         |     internalQuery: undefined,
api         |     where: "unnamed portal parameter $5 = '...'",
api         |     schema: undefined,
api         |     table: undefined,
api         |     column: undefined,
api         |     dataType: undefined,
api         |     constraint: undefined,
api         |     file: 'numutils.c',
api         |     line: '617',
api         |     routine: 'pg_strtoint32_safe'
api         |   },
api         |   length: 146,
api         |   severity: 'ERROR',
api         |   code: '22P02',
api         |   detail: undefined,
api         |   hint: undefined,
api         |   position: undefined,
api         |   internalPosition: undefined,
api         |   internalQuery: undefined,
api         |   where: "unnamed portal parameter $5 = '...'",
api         |   schema: undefined,
api         |   table: undefined,
api         |   column: undefined,
api         |   dataType: undefined,
api         |   constraint: undefined,
api         |   file: 'numutils.c',
api         |   line: '617',
api         |   routine: 'pg_strtoint32_safe'
api         | }
api         | 
api         | Node.js v20.16.0
```
